#! /bin/sh

if [ "$#" -gt 1 ]; then
    echo "Invalid number of arguments" 1>&2
    exit 1
fi
DIR=$([ -z "$1" ] && echo "./" || echo "$1")
if [ ! -d "$DIR" ]; then
    echo "$DIR is not a directory" 1>&2
    exit 1
fi
find "$DIR" -exec basename {} \; | grep -E ".{14,}|^-|^\.|[^a-zA-Z._-]" | grep -Evw ".|.."