#! /bin/sh

# check if there are more than 2 arguments
if [ "$#" -gt 2 ]; then
    echo "Invalid number of arguments" 1>&2
    exit 1
fi

# check if -r flag is present and set directory input accordingly
if [ "$1" = "-r" ]
then
    REC=0
    DIR=$([ -z "$2" ] && echo "." || echo "$2")
else
    REC=1
    DIR=$([ -z "$1" ] && echo "." || echo "$1")
fi
if [ ! -d "$DIR" ]; then
    echo "$DIR is not a directory" 1>&2
    exit 1
fi

# adjust maxdepth based on -r flag
if [ $REC -eq 0 ]
then
    find "$DIR" -exec sh -c 'path="$1"; name=$(basename "$1" | \grep -E \
    "[^a-zA-Z._-]|.{15,}|^-|^\." | grep -Evw "\.|\.\."); [ -n "$name" ] \
    && echo $path' _ {} \; 
    find "$DIR" | sort -f | uniq -Di
else
    find "$DIR" -maxdepth 1 -exec sh -c 'path="$1"; name=$(basename "$1" \
    | grep -E "[^a-zA-Z._-]|.{15,}|^-|^\." | grep -Evw "\.|\.\."); [ -n \
    "$name" ] && echo $path' _ {} \; 
    find "$DIR" -maxdepth 1 | sort -f | uniq -Di
fi