#! /bin/sh

is_poorname () {
    poor=0
    rule1=$(echo "$1" | grep "[^a-zA-Z._-]")
    if [ -n $rule1 ]; then
        poor=1
    fi
    rule2=$(echo "$1" | cut -c1-1)
    if [ $rule2 = "-" ]; then
        poor=1
    fi
    echo $rule2
}

find_poorname () {
    #if [ $# = 1 -o \( $(echo "$1" | cut -c1-1) = '-' \) ]; then
    #    echo "Invalid" 1>&2;
    #    exit 1;
    #fi
    # check if multiple input TODO: support -r
    if [ "$#" -gt 1 ]; then
        echo "Invalid argument" 1>&2;
        exit 1;
    fi
    DIR=$([ -z "$1" ] && echo "./" || echo "$1")
    # make sure input is a directory
    if [ ! -d $DIR ]; then
        echo "$DIR is not a directory" 1>&2;
        exit 1;
    fi
    # TODO: change find type to file and symlink
    find $DIR -maxdepth 1 | while read -r line; do
        filename=$(basename "$line")
        valid=$(echo "$filename" | grep "[^a-zA-Z._-]")
        if [ $(is_validname "$filename") -eq 0 ]; then
            echo $line
        fi
    done
}

is_poorname $@
#find_poorname $@

: '
for arg in "$@"
do
    if [ "$arg" == "-r" ] || [ "$arg" == "--recursive" ]
    then
        echo "recursive"
    fi
done
'